#!/bin/sh
# set -x

. /volume/config/sr.conf

startstream () {
  NAME="$1"
  URL="$2"
  DIR="$DATADIR/$NAME"
  echo "Starting DIR=$DIR URL=$URL"
  mkdir -p "$DIR"
  cd "$DIR"
  nohup streamripper "$URL" -s -d "$DIR" -k 2 -o always --quiet &
}

start () {
  for STREAM in  $CONFDIR/*.urls; do
    . "$STREAM"
    startstream "$NAME" "$URL"
  done
}

start

while true; do
  date
  sleep 60
done

